[project]
name = "yazyk"
version = "0.1.0"
description = "Django app to generate printable Russian language flashcards"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.7",
]
