name: Django CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv and setup Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
          **/uv.lock
          **/pyproject.toml
        python-version: ${{ matrix.python-version }}

    - name: Test with Django test runner
      run: |
        uv run --frozen manage.py test

    - name: Minimize uv cache
      run: uv cache prune --ci
